#!/usr/bin/env bash
set -euo pipefail

APP_NAME="BirdBros Recycle Co"
BUNDLE_ID="${BUNDLE_ID:-co.birdbros.recycleco}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
SIGN_IDENTITY="${SIGN_IDENTITY:-}"
APPLE_ID="${APPLE_ID:-}"
APPLE_TEAM_ID="${APPLE_TEAM_ID:-}"
APPLE_APP_PASSWORD="${APPLE_APP_PASSWORD:-}"

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This release builder must be run on macOS."
  exit 1
fi

if [[ ! -f "main.py" ]]; then
  echo "main.py not found. Run this from the packaging folder inside your BirdBros project folder."
  exit 1
fi

FIRST_RUN_README="packaging/FIRST_RUN_README.txt"
DMG_BACKGROUND="packaging/dmg_background.png"
DMG_BACKGROUND_ABS="$ROOT_DIR/$DMG_BACKGROUND"
ICON_PATH="assets/BirdBros.icns"

if [[ ! -f "$FIRST_RUN_README" ]]; then
  echo "Missing $FIRST_RUN_README"
  exit 1
fi

if [[ ! -f "$DMG_BACKGROUND" ]]; then
  echo "Missing $DMG_BACKGROUND"
  exit 1
fi

echo "==> Building ${APP_NAME} for macOS"

rm -rf build dist release
mkdir -p release

"$PYTHON_BIN" -m venv .venv_build
source .venv_build/bin/activate
python -m pip install --upgrade pip setuptools wheel
python -m pip install \
  pyinstaller \
  dmgbuild \
  PySide6 \
  opencv-python \
  numpy \
  mss \
  python-dotenv \
  openai

PYINSTALLER_COMMON_ARGS=(
  --noconfirm
  --clean
  --windowed
  --onedir
  --name "$APP_NAME"
  --osx-bundle-identifier "$BUNDLE_ID"
  --collect-all PySide6
  --hidden-import PySide6.QtCore
  --hidden-import PySide6.QtGui
  --hidden-import PySide6.QtWidgets
  --hidden-import api_key_store
  --hidden-import first_run_setup
  --hidden-import cv2
  --hidden-import mss
)

if [[ -f "$ICON_PATH" ]]; then
  pyinstaller "${PYINSTALLER_COMMON_ARGS[@]}" --icon "$ICON_PATH" main.py
else
  pyinstaller "${PYINSTALLER_COMMON_ARGS[@]}" main.py
fi

APP_PATH="dist/${APP_NAME}.app"
if [[ ! -d "$APP_PATH" ]]; then
  echo "Expected app bundle not found at: $APP_PATH"
  exit 1
fi

# Remove bundled PySide6 developer/helper apps that are not needed at runtime
# and can break Developer ID signing.
# Remove bundled PySide6 developer/helper apps that are not needed at runtime
# and can break Developer ID signing.
# Remove bundled PySide6 developer/helper apps that are not needed at runtime
# and can break Developer ID signing.
# Remove bundled PySide6 developer/helper apps that are not needed at runtime
# and can break Developer ID signing.
find "$APP_PATH" \
  \( \
    -name "Assistant__dot__app" -o \
    -name "Assistant.app" -o \
    -name "Designer__dot__app" -o \
    -name "Designer.app" -o \
    -name "Linguist__dot__app" -o \
    -name "Linguist.app" \
  \) \
  -prune \
  -exec rm -rf {} +

# Keep user-specific runtime files outside the app bundle.
mkdir -p "$HOME/Library/Application Support/${APP_NAME}"
mkdir -p "$HOME/Library/Logs/${APP_NAME}"

if [[ -n "$SIGN_IDENTITY" ]]; then
  echo "==> Signing app with: $SIGN_IDENTITY"
  codesign \
    --force \
    --deep \
    --options runtime \
    --entitlements packaging/entitlements.plist \
    --sign "$SIGN_IDENTITY" \
    "$APP_PATH"

  codesign --verify --deep --strict --verbose=2 "$APP_PATH"
else
  echo "==> No SIGN_IDENTITY provided; applying ad-hoc signature for local testing."
  codesign --force --deep --sign - "$APP_PATH"
fi

echo "==> Creating polished drag-to-Applications DMG with dmgbuild"

DMG_PATH="release/${APP_NAME// /_}_macOS.dmg"
DMG_STAGE="release/dmg_stage"
DMG_SETTINGS="release/dmgbuild_settings.py"

rm -f "$DMG_PATH"
rm -rf "$DMG_STAGE"
mkdir -p "$DMG_STAGE"

# Stage ONLY user-visible installer items.
# The background is referenced from packaging/dmg_background.png so it does not
# appear as a loose file in the mounted DMG.
ditto "$APP_PATH" "$DMG_STAGE/${APP_NAME}.app"

mkdir -p "$DMG_STAGE/.background"
cp "$DMG_BACKGROUND" "$DMG_STAGE/.background/dmg_background.png"

APP_SIZE_MB="$(du -sm "$APP_PATH" | awk '{print $1}')"
DMG_SIZE_MB=$(( APP_SIZE_MB + 350 ))
if [[ "$DMG_SIZE_MB" -lt 700 ]]; then
  DMG_SIZE_MB=700
fi

echo "==> App size: ${APP_SIZE_MB} MB | DMG size: ${DMG_SIZE_MB} MB"

cat > "$DMG_SETTINGS" <<PYSETTINGS
# Generated by packaging/build_macos_release.sh
# dmgbuild writes Finder .DS_Store layout metadata directly.
# Visible installer items are intentionally limited to the app and Applications alias.

format = 'UDZO'
size = '${DMG_SIZE_MB}M'
filesystem = 'HFS+'

files = [
    '${APP_NAME}.app',
]

symlinks = {
    'Applications': '/Applications',
}

badge_icon = None
background = '.background/dmg_background.png'
show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False

window_rect = ((160, 110), (900, 520))
default_view = 'icon-view'
show_icon_preview = False
include_icon_view_settings = 'auto'
include_list_view_settings = False

arrange_by = None
grid_offset = (0, 0)
grid_spacing = 100
scroll_position = (0, 0)
label_pos = 'bottom'
text_size = 12
icon_size = 116

icon_locations = {
    '${APP_NAME}.app': (235, 265),
    'Applications': (665, 265),
}
PYSETTINGS

(
  cd "$DMG_STAGE"
  dmgbuild -s "../dmgbuild_settings.py" "$APP_NAME" "../${APP_NAME// /_}_macOS.dmg"
)

rm -rf "$DMG_STAGE"
rm -f "$DMG_SETTINGS"

if [[ ! -f "$DMG_PATH" ]]; then
  echo "DMG was not created at expected path: $DMG_PATH"
  exit 1
fi

if [[ -n "$SIGN_IDENTITY" ]]; then
  echo "==> Signing DMG"
  codesign --force --sign "$SIGN_IDENTITY" "$DMG_PATH"
fi

if [[ -n "$APPLE_ID" && -n "$APPLE_TEAM_ID" && -n "$APPLE_APP_PASSWORD" ]]; then
  echo "==> Submitting DMG for Apple notarization"
  xcrun notarytool submit "$DMG_PATH" \
    --apple-id "$APPLE_ID" \
    --team-id "$APPLE_TEAM_ID" \
    --password "$APPLE_APP_PASSWORD" \
    --wait

  echo "==> Stapling notarization ticket"
  xcrun stapler staple "$DMG_PATH"
else
  echo "==> Skipping notarization. Set APPLE_ID, APPLE_TEAM_ID, and APPLE_APP_PASSWORD to notarize."
fi

echo ""
echo "DONE"
echo "DMG created at: $DMG_PATH"
echo ""
echo "User install flow: open DMG -> drag BirdBros Recycle Co.app to Applications -> launch."
echo "First launch may require Screen Recording permission in System Settings."
